essai 3

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -44,12 +44,12 @@ jobs:
               run: make clean
             - name: Verify executables
               run: |
-                IFS=',' read -ra ADDR <<< "$EXECUTABLES"
-                for i in "${ADDR[@]}"; do
-                    if [ ! -x "$i" ]; then
-                        echo "Executable $i not found or not executable"
-                        exit 1
-                    fi
+                IFS=',' read -ra BINARIES <<< "$EXECUTABLES"
+                for binary in "${BINARIES[@]}"; do
+                  if [ ! -x "$binary" ]; then
+                    echo "::error file=$binary,title=Binary Error::Executable '$binary' missing or not executable"
+                    exit 1
+                  fi
                 done
     run_tests:
         name: Run unit tests
